# Generated by Django 4.2 on 2023-04-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=22)),
                ('last_name', models.CharField(max_length=22)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(max_length=22)),
                ('country', models.CharField(max_length=22)),
                ('state', models.CharField(max_length=22)),
                ('town', models.CharField(max_length=22)),
                ('zipcode', models.IntegerField(default=0)),
                ('phonenumber1', models.IntegerField(default=0)),
                ('phonenumber2', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
